#include "../include/alu.h"
#include "../include/clock.h"
#include "../include/cpu.h"
#include "../include/memory.h"
#include <fstream>
#include <iostream>

int main() {
  MemoryManager ram;
  ALU alu;
  Clock systemClock;
  CPU cpu(ram, alu, systemClock);

  // Load the binary file generated by your assembler
  std::ifstream infile("machine_code.bin", std::ios::binary);
  if (!infile) {
    std::cerr << "Error: machine_code.bin not found. Run assembler first.\n";
    return 1;
  }

  uint16_t instr;
  uint16_t addr = 0;
  while (infile.read(reinterpret_cast<char *>(&instr), sizeof(instr))) {
    ram.write(addr, instr);
    addr++;
  }

  std::cout << "\n--- CPU BOOT SEQUENCE INITIATED ---\n";

  // Increased to 200 cycles to allow longer programs to run
  for (int i = 0; i < 200; i++) {
    cpu.cycle();
    // Kill switch: Stop the clock if the Instruction Register hits HALT
    // (0x9000)
    if (cpu.registers()[ISA::IR] == 0x9000)
      break;
  }

  std::cout << "\n--- CPU SHUTDOWN ---\n";
  return 0;
}
