#include "../include/alu.h"
#include "../include/clock.h"
#include "../include/cpu.h"
#include "../include/memory.h"
#include <fstream>
#include <getopt.h>
#include <iostream>
#include <string>

void printDebugMenu() {
  std::cout << "-------------------------------------------------" << std::endl;
  std::cout << "help menu: \n q - quit, n - next instruction, 1 - print cpu "
               "state, 2 - "
               "memory dump"
            << std::endl;
  std::cout << "-------------------------------------------------" << std::endl;
}

int main(int argc, char *argv[]) {
  bool verbose = false;
  bool debugger = false;
  int opt;
  while ((opt = getopt(argc, argv, "vd")) != -1) {
    if (opt == 'v') {
      verbose = true;
    }
    if (opt == 'd') {
      debugger = true;
    }
  }

  MemoryManager ram;
  ALU alu;
  Clock systemClock;
  CPU cpu(ram, alu, systemClock);

  // Load the binary file generated by your assembler
  std::ifstream infile("machine_code.bin", std::ios::binary);
  if (!infile) {
    std::cerr << "Error: machine_code.bin not found. Run assembler first.\n";
    return 1;
  }

  uint16_t instr;
  uint16_t addr = 0;
  while (infile.read(reinterpret_cast<char *>(&instr), sizeof(instr))) {
    ram.write(addr, instr);
    addr++;
  }

  std::cout << "\n--- CPU BOOT SEQUENCE INITIATED ---\n";

  if (debugger) {
    std::cout << "\n -- ENTERING DEBUG MODE -- \n";
    printDebugMenu();
    std::string line;
    while (cpu.checkHalt()) {
      std::cout << "> ";
      if (!std::getline(std::cin, line))
        break;
      if (line.empty()) {
        printDebugMenu();
        continue;
      }
      char command = line[0];
      switch (command) {
      case 'n':
        cpu.cycle();
        break;
      case '1':
        cpu.printState();
        break;
      case '2':
        cpu.memoryDump();
        break;
      case 'q':
        return 0;
      default:
        printDebugMenu();
      }
    }
  } else {
    int MAX_ITER = 200;
    int curr_iter = 0;
    if (verbose)
      cpu.printState();
    while (curr_iter++ < MAX_ITER && cpu.checkHalt()) {
      cpu.cycle();
      if (verbose)
        cpu.printState();
    }
  }

  std::cout << "\n--- CPU SHUTDOWN ---\n";
  return 0;
}
